Repository pknu-wap/2025_1_Embedded1_TTALKKAG, pull requests merged in 2025-04, with the labels that each got.

#12 11-feat 디바이스목록페이지 디바이스박스 구현
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#15 3-feat-deviceCRUD
  server/ttalkkag/springboot-client-tcplocalhost1883/.lck
  server/ttalkkag/src/main/java/wap/ttalkkag/device/ChangeDeviceSettingDTO.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeleteDeviceDTO.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Button.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Dial.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Door.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Trigger.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/TriggerId.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/User.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/enums/DeviceType.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttPublisherSevice.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttSubscriberService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/ButtonRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/DialRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/DoorRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/TriggerRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/UserRepository.java
  server/ttalkkag/src/main/resources/application-local.properties
Labels: enhancement, BE

#22 19-feat-버튼-원격-조정-기능
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttPublisherSevice.java
Labels: enhancement, BE

#25 24-feat-mqtt-브로커-연결-코드-수정
  server/ttalkkag/.gitignore
  server/ttalkkag/springboot-client-tcplocalhost1883/.lck
  server/ttalkkag/src/main/java/wap/ttalkkag/config/MqttConfig.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttPublisherSevice.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttSubscriberService.java
  server/ttalkkag/src/main/resources/application-prob.properties
Labels: enhancement, BE

#26 remove properties file from git tracking
  server/ttalkkag/src/main/resources/application-prob.properties
Labels: BE

#28 27 feat 디바이스목록페이지 디바이스박스 토글로 늘어나기
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/screens/DevicePage/components/DeviceBox.js
  client/yarn.lock
  package-lock.json
  package.json
Labels: enhancement, FE

#30 29-feat 디바이스목록페이지 디바이스박스 에셋추가와 세부기능 추가
  client/assets/device_icon.png
  client/assets/power_off.png
  client/assets/power_on.png
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#32 32-feat 앱 로딩 화면 구현하기
  client/App.tsx
  client/assets/Loading.png
  client/src/screens/LoadingPage.js
Labels: enhancement, FE

#34 34-feat 하단 네비게이션바 아이콘 추가
  client/App.tsx
  client/assets/DeviceNav.png
  client/assets/TriggerNav.png
Labels: enhancement, FE

#38 37 feat 디바이스목록페이지 글자배치 토글버튼 위치조정
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/AppText.js
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#36 35-feat 디바이스목록페이지 하단 네비게이션바 수정
  client/src/screens/DevicePage/DPage.js
Labels: enhancement, FE

#42 41-feat 디바이스목록페이지 디바이스박스 이름 수정 기능 추가
  client/src/api/deviceApi.js
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE
