Repository pknu-wap/2025_1_Embedded1_TTALKKAG, pull requests merged in 2025-05, with the labels that each got.

#44 44-feat 디바이스목록페이지 스와이프로 삭제기능 추가
  client/App.tsx
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/api/deviceApi.js
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/DeviceBox.js
  client/yarn.lock
Labels: enhancement, FE

#48 45-bug 디바이스목록페이지 전원버튼 반응성 버그 수정
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: bug, FE

#47 46-feat 디바이스 메모 저장
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/PatchDeviceMemoDTO.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Button.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Dial.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Door.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttPublisherSevice.java
Labels: enhancement, BE

#62 59-feat-트리거 목록 불러오기
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Button.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Dial.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Door.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Trigger.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/enums/DeviceType.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/DoorRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/TriggerRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/trigger/TriggerController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/trigger/TriggerService.java
Labels: enhancement, BE

#66 61-feat 디바이스 목록페이지 다이얼 토글창 하단 정보 구현
  client/android/app/build.gradle
  client/android/gradle.properties
  client/assets/dial_bg.png
  client/assets/down.png
  client/assets/up.png
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#67 57 feat 트리거페이지 배경 및 상단텍스트 구현
  client/App.tsx
  client/src/screens/DevicePage/AnotherPage.js
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/AppText.js
  client/src/screens/TriggerPage/components/Background.js
  client/src/screens/TriggerPage/index.js
Labels: enhancement, FE

#77 feat:컨포넌트 추가
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#78 76-feat트리거목록페이지-목록ui
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#85 84-feat디바이스 박스 구현
  client/assets/Subtract.png
  client/assets/TriggerDeviceBox_off.png
  client/assets/TriggerDeviceBox_on.png
  client/assets/setting_icon.png
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerDeviceBox.js
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#83 81-feat-디바이스가 속한 트리거 목록 mqtt 통신으로 회신
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttSubscriberService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/ButtonRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/DialRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/DoorRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/TriggerRepository.java
Labels: enhancement, BE

#87 86-feat트리거페이지-전체적인-디테일-수정
  client/assets/TriggerDeviceBox_on.png
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerDeviceBox.js
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#89 88-feat-디바이스 목록페이지 스탭각도 조절 기능 추가
  bash.exe.stackdump
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#93 92-feat-다이얼 스텝 관련 코드 수정 및 작성
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Dial.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Door.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttSubscriberService.java
Labels: enhancement, BE

#94 91-feat-디바이스 목록페이지 다이얼 통신 기능 구현
  client/src/api/deviceApi.js
  client/src/screens/DevicePage/DPage.js
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#95 90-feat트리거 목록 삭제 기능
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#99 99-feat-디바이스목록페이지 디바이스 아이콘 수정
  client/assets/button_icon.png
  client/assets/dial_icon.png
  client/assets/toggle-down.png
  client/assets/toggle-right.png
  client/src/screens/DevicePage/components/DeviceBox.js
Labels: enhancement, FE

#103 102-feat-디바이스목록페이지 디자인 수정
  client/App.tsx
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/res/mipmap-hdpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-ldpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-mdpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xhdpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xxhdpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xxxhdpi-v26/ic_foreground.png
  client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  client/android/app/src/main/res/values/strings.xml
  client/assets/Loading.png
  client/assets/app_icon.png
  client/assets/app_icon1.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-1024@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-20@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-20@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-20@3x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-29@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-29@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-29@3x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-40@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-40@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-40@3x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-50@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-50@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-57@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-57@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-60@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-60@3x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-72@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-72@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-76@1x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-76@2x.png
  client/ios/and/Images.xcassets/AppIcon.appiconset/icon-83.5@2x.png
  client/package-lock.json
  client/package.json
  client/src/screens/DevicePage/components/DeviceBox.js
  client/yarn.lock
Labels: enhancement, FE

#100 97-feat트리거페이지 통신연결
  client/src/api/triggerApi.js
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerDeviceBox.js
Labels: enhancement, FE

#106 105-feat디바이스아이콘,삭제ui
  client/assets/button_icon.png
  client/assets/dial_icon.png
  client/src/api/triggerApi.js
  client/src/screens/TriggerPage/TPage.js
  client/src/screens/TriggerPage/components/TriggerDeviceBox.js
  client/src/screens/TriggerPage/components/TriggerList.js
Labels: enhancement, FE

#104 101-feat-트리거 추가 및 기존 코드 수정
  server/ttalkkag/src/main/java/wap/ttalkkag/device/DeviceService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/Trigger.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/TriggerDevice.java
  server/ttalkkag/src/main/java/wap/ttalkkag/domain/TriggerId.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/mqtt/MqttSubscriberService.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/TriggerDeviceRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/repository/TriggerRepository.java
  server/ttalkkag/src/main/java/wap/ttalkkag/trigger/ActivateDeviceDTO.java
  server/ttalkkag/src/main/java/wap/ttalkkag/trigger/TriggerController.java
  server/ttalkkag/src/main/java/wap/ttalkkag/trigger/TriggerService.java
Labels: enhancement, BE
